/*
 * test_tokenizer.c — Verification and benchmark for the pure-C BPE tokenizer.
 *
 *   build/test_tokenizer TOKENIZER.json GOLDEN.txt [--tmpdir DIR]
 *
 *   1. Golden parity: every case in GOLDEN.txt (generated by
 *      tools/gen_tokenizer_golden.py with HF tokenizers) must encode to exactly
 *      the same ids, and decode(encode(text)) must equal text byte-for-byte.
 *   2. Unit tests: random/invalid UTF-8 bytes round-trip, truncation contract,
 *      special-token handling on/off, id lookups, invalid ids, every vocab
 *      token round-trips, concurrent encoding from multiple threads.
 *   3. Robustness: malformed tokenizer files must fail cleanly (no crash/leak).
 *   4. Benchmark: load time, encode and decode throughput.
 *
 * Build & run: `make test` (binary: build/test_tokenizer); `make asan` for sanitizers.
 */

#define _POSIX_C_SOURCE 200809L
#define _DEFAULT_SOURCE
#define _DARWIN_C_SOURCE

#undef NDEBUG /* verification asserts must always run */
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include "platform.h"
#include "threadpool.h"
#include "tokenizer.h"

static inline uint64_t now_ns(void) { return platform_now_ns(); }

static char *read_file(const char *path, size_t *size) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        perror(path);
        exit(EXIT_FAILURE);
    }
    fseek(f, 0, SEEK_END);
    const long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t)n + 1);
    assert(buf && n >= 0 && fread(buf, 1, (size_t)n, f) == (size_t)n);
    fclose(f);
    buf[n] = '\0';
    *size = (size_t)n;
    return buf;
}

/* ------------------------------------------------------------------------- */
/* Golden cases                                                              */
/* ------------------------------------------------------------------------- */

typedef struct {
    char    *label;
    char    *text;
    size_t   len;
    int32_t *ids;
    int      n_ids;
} golden_case;

static int hexv(char c) {
    return c >= '0' && c <= '9' ? c - '0' : c >= 'a' && c <= 'f' ? c - 'a' + 10 : -1;
}

static golden_case *load_golden(const char *path, int *n_cases) {
    size_t size;
    char *buf = read_file(path, &size);
    int cap = 4096, n = 0;
    golden_case *cases = malloc((size_t)cap * sizeof(*cases));
    assert(cases);
    for (char *line = strtok(buf, "\n"); line; line = strtok(NULL, "\n")) {
        if (line[0] == '#') continue;
        char *tab1 = strchr(line, '\t');
        assert(tab1);
        char *tab2 = strchr(tab1 + 1, '\t');
        assert(tab2);
        if (n == cap) {
            cap *= 2;
            cases = realloc(cases, (size_t)cap * sizeof(*cases));
            assert(cases);
        }
        golden_case *g = &cases[n++];
        *tab1 = *tab2 = '\0';
        g->label = strdup(line);
        const size_t hex_len = (size_t)(tab2 - tab1 - 1);
        assert(hex_len % 2 == 0);
        g->len = hex_len / 2;
        g->text = malloc(g->len + 1);
        assert(g->label && g->text);
        for (size_t i = 0; i < g->len; i++) {
            const int hi = hexv(tab1[1 + 2 * i]), lo = hexv(tab1[2 + 2 * i]);
            assert(hi >= 0 && lo >= 0);
            g->text[i] = (char)(hi << 4 | lo);
        }
        g->text[g->len] = '\0';
        int idcap = 16;
        g->ids = malloc((size_t)idcap * sizeof(int32_t));
        g->n_ids = 0;
        for (char *p = tab2 + 1; *p;) {
            char *e;
            const long v = strtol(p, &e, 10);
            if (e == p) break;
            if (g->n_ids == idcap) {
                idcap *= 2;
                g->ids = realloc(g->ids, (size_t)idcap * sizeof(int32_t));
                assert(g->ids);
            }
            g->ids[g->n_ids++] = (int32_t)v;
            p = e;
        }
    }
    free(buf);
    *n_cases = n;
    return cases;
}

static void free_golden(golden_case *c, int n) {
    for (int i = 0; i < n; i++) {
        free(c[i].label);
        free(c[i].text);
        free(c[i].ids);
    }
    free(c);
}

static void print_tokens(const Tokenizer *t, const int32_t *ids, int n, int from) {
    for (int i = from; i < n && i < from + 8; i++) {
        size_t l;
        const char *s = bpe_decode_bytes(t, ids[i], &l);
        printf(" %d:\"", ids[i]);
        for (size_t k = 0; s && k < l; k++)
            printf((unsigned char)s[k] >= 0x20 && s[k] != '"' ? "%c" : "\\x%02x", (unsigned char)s[k]);
        printf("\"");
    }
    printf("\n");
}

static void verify_golden(const Tokenizer *t, golden_case *cases, int n) {
    int32_t *ids = malloc(64 * 1024 * sizeof(int32_t));
    char *dec = malloc(256 * 1024);
    assert(ids && dec);
    long total_tokens = 0;
    size_t total_bytes = 0;
    for (int c = 0; c < n; c++) {
        const golden_case *g = &cases[c];
        const int got = bpe_encode_ex(t, g->text, g->len, ids, 64 * 1024, 0);
        int bad = got != g->n_ids ? (got < g->n_ids ? got : g->n_ids) : -1;
        for (int i = 0; bad < 0 && i < got; i++)
            if (ids[i] != g->ids[i]) bad = i;
        if (bad >= 0) {
            printf("GOLDEN MISMATCH %s (len %zu): got %d tokens, want %d, first diff at %d\n  got :",
                   g->label, g->len, got, g->n_ids, bad);
            print_tokens(t, ids, got, bad > 2 ? bad - 2 : 0);
            printf("  want:");
            print_tokens(t, g->ids, g->n_ids, bad > 2 ? bad - 2 : 0);
            exit(EXIT_FAILURE);
        }
        const long dl = bpe_decode_tokens(t, ids, got, dec, 256 * 1024);
        assert(dl == (long)g->len && memcmp(dec, g->text, g->len) == 0);
        total_tokens += got;
        total_bytes += g->len;
    }
    free(ids);
    free(dec);
    printf("Golden parity:  PASSED (%d cases, %zu bytes, %ld tokens: ids == HF tokenizers, "
           "decode(encode(x)) == x)\n", n, total_bytes, total_tokens);
}

/* ------------------------------------------------------------------------- */
/* Unit tests                                                                */
/* ------------------------------------------------------------------------- */

static uint64_t rng = 0x243F6A8885A308D3ull;
static uint64_t rnd(void) {
    rng ^= rng << 13;
    rng ^= rng >> 7;
    rng ^= rng << 17;
    return rng;
}

static void roundtrip(const Tokenizer *t, const char *s, size_t n, unsigned flags) {
    int32_t ids[8192];
    char dec[16384];
    const int k = bpe_encode_ex(t, s, n, ids, 8192, flags);
    assert(k >= 0 && k <= 8192);
    const long dl = bpe_decode_tokens(t, ids, k, dec, sizeof(dec));
    assert(dl == (long)n && memcmp(dec, s, n) == 0);
    /* Streaming: per-token decode concatenates to the same bytes. */
    size_t off = 0;
    for (int i = 0; i < k; i++) {
        size_t l;
        const char *p = bpe_decode_bytes(t, ids[i], &l);
        assert(p && off + l <= n && memcmp(s + off, p, l) == 0);
        off += l;
    }
    assert(off == n);
}

static void unit_tests(const Tokenizer *t) {
    int cases = 0;

    /* Arbitrary bytes, including invalid UTF-8, NULs, lone continuation bytes,
     * overlong encodings and surrogates, round-trip exactly. */
    static const char *const invalid[] = {
        "\xff", "\xc0\x80", "\xed\xa0\x80", "\xf4\x90\x80\x80", ("\x80\x80" "abc"), "abc\xe2\x82",
        "\xe2\x82\xac\xe2\x82", "caf\xc3", "\xf0\x9f\x98", "a\xfe\xfe b\xff\n", "\xc3\x28",
    };
    for (size_t i = 0; i < sizeof(invalid) / sizeof(invalid[0]); i++, cases++)
        roundtrip(t, invalid[i], strlen(invalid[i]), 0);
    char buf[2048];
    for (int r = 0; r < 3000; r++, cases++) {
        const size_t n = rnd() % sizeof(buf);
        const int mode = (int)(rnd() % 3);
        for (size_t i = 0; i < n; i++) {
            const uint64_t x = rnd();
            buf[i] = mode == 0 ? (char)x                                      /* any byte */
                   : mode == 1 ? " \n\t'aZ09<|>\xc3\xa9"[x % 14]              /* ASCII-heavy */
                               : (char)(0x80 | (x & 0x7F));                   /* continuation soup */
        }
        roundtrip(t, buf, n, (unsigned)(r & 1));
    }

    /* Truncation contract: returns the full count, writes at most max. */
    {
        const char *s = "The quick brown fox jumps over the lazy dog";
        int32_t full[64], part[4] = {-7, -7, -7, -7};
        const int n = bpe_encode(t, s, full, 64);
        assert(n == 9);
        assert(bpe_encode(t, s, part, 3) == n);
        assert(memcmp(part, full, 3 * sizeof(int32_t)) == 0 && part[3] == -7);
        assert(bpe_encode(t, s, NULL, 0) == n);
        assert(bpe_encode(t, "", full, 64) == 0);
        assert(bpe_encode(NULL, s, full, 64) == -1 && bpe_encode(t, NULL, full, 64) == -1);
        assert(bpe_encode(t, s, NULL, 5) == -1 && bpe_encode(t, s, full, -1) == -1);
        cases += 8;
    }

    /* Special tokens: matched by default, plain text with TOKENIZER_NO_SPECIAL. */
    {
        const int32_t bos = tokenizer_token_id(t, "<|begin_of_text|>");
        const int32_t eot = tokenizer_token_id(t, "<|eot_id|>");
        assert(bos == 128000 && eot == 128009);
        assert(tokenizer_is_special(t, bos) && tokenizer_is_special(t, eot));
        assert(!tokenizer_is_special(t, 9906) && !tokenizer_is_special(t, -1) &&
               !tokenizer_is_special(t, 1 << 30));
        assert(tokenizer_token_id(t, "Hello") == 9906 && tokenizer_token_id(t, " world") == 1917);
        assert(tokenizer_token_id(t, "definitely not a single token") == -1);

        const char *s = "a<|eot_id|>b";
        int32_t ids[32];
        int n = bpe_encode(t, s, ids, 32);
        assert(n == 3 && ids[1] == eot);
        n = bpe_encode_ex(t, s, strlen(s), ids, 32, TOKENIZER_NO_SPECIAL);
        assert(n > 3);
        for (int i = 0; i < n; i++) assert(!tokenizer_is_special(t, ids[i]));
        roundtrip(t, s, strlen(s), TOKENIZER_NO_SPECIAL);
        assert(strcmp(bpe_decode(t, eot), "<|eot_id|>") == 0);
        cases += 10;
    }

    /* Invalid ids. */
    {
        assert(bpe_decode(t, -1) == NULL && bpe_decode(t, tokenizer_vocab_size(t)) == NULL);
        const int32_t bad[2] = {9906, 999999};
        char out[16];
        assert(bpe_decode_tokens(t, bad, 2, out, sizeof(out)) == -1);
        /* Byte 0x00 token: empty C string, exact length 1 via bpe_decode_bytes. */
        int32_t z;
        assert(bpe_encode_ex(t, "\0", 1, &z, 1, 0) == 1);
        size_t l;
        const char *p = bpe_decode_bytes(t, z, &l);
        assert(l == 1 && p[0] == '\0');
        cases += 4;
    }

    /* Every id decodes, and its bytes round-trip through encode. Count how
     * many tokens are reproduced as themselves (informational). */
    int self = 0;
    const int V = tokenizer_vocab_size(t);
    for (int32_t id = 0; id < V; id++) {
        size_t l;
        const char *p = bpe_decode_bytes(t, id, &l);
        assert(p && strlen(p) <= l);
        int32_t ids[512];
        const int n = bpe_encode_ex(t, p, l, ids, 512, 0);
        assert(n >= 1 && n <= 512);
        self += n == 1 && ids[0] == id;
        roundtrip(t, p, l, 0);
    }
    cases += V;

    printf("Unit tests:     PASSED (%d cases; invalid UTF-8 & random bytes round-trip, truncation, "
           "specials on/off, all %d ids decode + round-trip; %d encode to themselves)\n",
           cases, V, self);
}

/* Concurrent encoding from worker threads must equal serial results. */
typedef struct {
    const Tokenizer   *t;
    const golden_case *cases;
    int                failures;
} conc_ctx;

static void encode_one(void *ctx_, size_t i) {
    conc_ctx *c = ctx_;
    const golden_case *g = &c->cases[i];
    int32_t *ids = malloc((size_t)(g->n_ids + 1) * sizeof(int32_t));
    const int k = bpe_encode_ex(c->t, g->text, g->len, ids, g->n_ids + 1, 0);
    if (k != g->n_ids || memcmp(ids, g->ids, (size_t)k * sizeof(int32_t)) != 0)
        __atomic_fetch_add(&c->failures, 1, __ATOMIC_RELAXED);
    free(ids);
}

static void concurrency_test(const Tokenizer *t, golden_case *cases, int n) {
    char err[64];
    threadpool *pool = threadpool_create(0, err, sizeof(err));
    assert(pool);
    conc_ctx c = {t, cases, 0};
    threadpool_run(pool, (size_t)n, &c, encode_one);
    assert(c.failures == 0);
    printf("Concurrency:    PASSED (%d cases encoded in parallel on %d threads, identical to golden)\n",
           n, threadpool_size(pool));
    threadpool_destroy(pool);
}

/* ------------------------------------------------------------------------- */
/* Malformed tokenizer files                                                 */
/* ------------------------------------------------------------------------- */

static void write_file(const char *path, const char *data, size_t n) {
    FILE *f = fopen(path, "wb");
    assert(f && fwrite(data, 1, n, f) == n);
    fclose(f);
}

static void robustness_tests(const char *json_path, const char *tmpdir) {
    size_t size;
    char *real = read_file(json_path, &size);
    char path[1024];
    snprintf(path, sizeof(path), "%s/tok_bad_%d.json", tmpdir, (int)getpid());

    char deep[4096] = "{\"a\": ";
    memset(deep + 6, '[', 3000);
    deep[3006] = '\0';
    /* Real file with the pre-tokenizer pattern altered. */
    char *altered = malloc(size + 1);
    memcpy(altered, real, size + 1);
    char *pat = strstr(altered, "\\\\p{N}{1,3}");
    assert(pat);
    pat[9] = '4'; /* {1,3} -> {1,4} */
    /* Real file whose first merge "Ġ Ġ" becomes "Ā Ġ" (bytes 0x00 + 0x20): both
     * sides exist but the merged token does not, so the load must fail. */
    char *badmerge = malloc(size + 1);
    memcpy(badmerge, real, size + 1);
    char *m = strstr(badmerge, "\"merges\"");
    assert(m && (m = strchr(m, '[')) && (m = strchr(m, '"')));
    assert(memcmp(m, "\"\xc4\xa0 \xc4\xa0\"", 7) == 0);
    m[2] = (char)0x80; /* U+0120 'Ġ' (C4 A0) -> U+0100 'Ā' (C4 80) */

    static const char sp_model[] = "\x0a\x0b\x0a\x05<unk>\x15\x00\x00\x00\x00\x18\x02";
    const struct { const char *what; const char *data; size_t n; const char *expect; } cases[] = {
        {"empty file", "", 0, "not a tokenizer.json"},
        {"SentencePiece protobuf", sp_model, sizeof(sp_model) - 1, "SentencePiece"},
        {"truncated JSON", real, 4000, "JSON parse error"},
        {"3000-deep nesting", deep, 3006, "nesting too deep"},
        {"no model", "{\"version\": \"1.0\"}", 18, "unsupported model type"},
        {"WordPiece model", "{\"model\": {\"type\": \"WordPiece\"}}", 33, "unsupported model type"},
        {"bad escape", "{\"a\": \"\\q\"}", 11, "bad escape"},
        {"lone surrogate", "{\"a\": \"\\ud800x\"}", 16, "unpaired surrogate"},
        {"altered regex", altered, size, "unsupported pre_tokenizer"},
        {"merge to unknown token", badmerge, size, "merge 0"},
    };
    const int n = (int)(sizeof(cases) / sizeof(cases[0]));
    for (int i = 0; i < n; i++) {
        write_file(path, cases[i].data, cases[i].n);
        char err[256] = {0};
        Tokenizer *t = tokenizer_load(path, err, sizeof(err));
        const int ok = t == NULL && strstr(err, cases[i].expect) != NULL;
        printf("  %-26s %s  %s\n", cases[i].what, ok ? "rejected" : "NOT CAUGHT", err);
        assert(ok);
    }
    char err[256] = {0};
    assert(tokenizer_load("/nonexistent/tokenizer.json", err, sizeof(err)) == NULL);
    tokenizer_free(NULL);
    unlink(path);
    free(real);
    free(altered);
    free(badmerge);
    printf("Robustness:     PASSED (%d malformed files rejected cleanly + missing file)\n", n);
}

/* ------------------------------------------------------------------------- */
/* Benchmark                                                                 */
/* ------------------------------------------------------------------------- */

static void benchmark(const char *json_path, golden_case *cases, int n) {
    enum { LOADS = 5, REPS = 20 };
    double best_load = 1e30;
    for (int i = 0; i < LOADS; i++) {
        char err[256];
        const uint64_t t0 = now_ns();
        Tokenizer *t = tokenizer_load(json_path, err, sizeof(err));
        const double ms = (double)(now_ns() - t0) / 1e6;
        assert(t);
        tokenizer_free(t);
        if (ms < best_load) best_load = ms;
    }

    char err[256];
    Tokenizer *t = tokenizer_load(json_path, err, sizeof(err));
    assert(t);
    int32_t *ids = malloc(64 * 1024 * sizeof(int32_t));
    char *dec = malloc(256 * 1024);
    size_t bytes = 0;
    long tokens = 0;
    for (int c = 0; c < n; c++) bytes += cases[c].len;

    double enc_best = 1e30, dec_best = 1e30;
    for (int r = 0; r < REPS; r++) {
        uint64_t t0 = now_ns();
        long tk = 0;
        for (int c = 0; c < n; c++) tk += bpe_encode_ex(t, cases[c].text, cases[c].len, ids, 64 * 1024, 0);
        const double enc = (double)(now_ns() - t0) / 1e9;
        t0 = now_ns();
        for (int c = 0; c < n; c++) bpe_decode_tokens(t, cases[c].ids, cases[c].n_ids, dec, 256 * 1024);
        const double dc = (double)(now_ns() - t0) / 1e9;
        if (enc < enc_best) enc_best = enc;
        if (dc < dec_best) dec_best = dc;
        tokens = tk;
    }
    printf("\nBenchmark (single thread, best of %d over the %d golden cases = %.0f KB)\n", REPS, n,
           bytes / 1024.0);
    printf("  load tokenizer.json (9.1 MB)   %8.1f ms\n", best_load);
    printf("  encode                         %8.2f ms   %6.1f MB/s   %5.2f M tokens/s\n",
           enc_best * 1e3, bytes / enc_best / 1e6, tokens / enc_best / 1e6);
    printf("  decode                         %8.2f ms   %6.1f MB/s   %5.1f M tokens/s\n",
           dec_best * 1e3, bytes / dec_best / 1e6, tokens / dec_best / 1e6);
    free(ids);
    free(dec);
    tokenizer_free(t);
}

int main(int argc, char **argv) {
    const char *json = NULL, *golden = NULL, *tmpdir = getenv("TMPDIR");
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--tmpdir") == 0 && i + 1 < argc) tmpdir = argv[++i];
        else if (!json) json = argv[i];
        else if (!golden) golden = argv[i];
    }
    if (!json || !golden) {
        fprintf(stderr, "usage: %s TOKENIZER.json GOLDEN.txt [--tmpdir DIR]\n", argv[0]);
        return 2;
    }
    if (!tmpdir) tmpdir = "/tmp";

    char err[256];
    Tokenizer *t = tokenizer_load(json, err, sizeof(err));
    if (!t) {
        fprintf(stderr, "load failed: %s\n", err);
        return 1;
    }
    printf("Tokenizer: %d ids\n", tokenizer_vocab_size(t));

    int n;
    golden_case *cases = load_golden(golden, &n);
    verify_golden(t, cases, n);
    unit_tests(t);
    concurrency_test(t, cases, n);
    tokenizer_free(t);

    printf("\nMalformed tokenizer files:\n");
    robustness_tests(json, tmpdir);
    benchmark(json, cases, n);
    free_golden(cases, n);
    return 0;
}
