#!/usr/bin/env python3
"""
gen_unicode_tables.py — Generate src/unicode_tables.h (code point ranges for the
\\p{L} and \\p{N} classes used by the tokenizer's pre-tokenizer regex).

The Unicode version must match the regex engine inside Hugging Face
`tokenizers` (Oniguruma), otherwise letters/digits from newer scripts would be
split differently. Probing tokenizers 0.22.2 shows Unicode 16.0: letters added
in 16.0 are \\p{L}, letters added in 17.0 are not.

Usage:
  curl -O https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
  python3 tools/gen_unicode_tables.py UnicodeData.txt > src/unicode_tables.h
"""

import sys


def load_categories(path):
    """Returns {code point: general category}, expanding <..., First>/<..., Last> ranges."""
    cats = {}
    with open(path, encoding="utf-8") as f:
        rows = [line.rstrip("\n").split(";") for line in f if line.strip()]
    i = 0
    while i < len(rows):
        cp, name, cat = int(rows[i][0], 16), rows[i][1], rows[i][2]
        if name.endswith(", First>"):
            last = int(rows[i + 1][0], 16)
            for c in range(cp, last + 1):
                cats[c] = cat
            i += 2
            continue
        cats[cp] = cat
        i += 1
    return cats


def ranges(cps):
    out = []
    for c in sorted(cps):
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


def emit(name, rs):
    lines = [f"static const uint32_t {name}[][2] = {{"]
    row = []
    for lo, hi in rs:
        row.append(f"{{0x{lo:05X}, 0x{hi:05X}}}")
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    cats = load_categories(sys.argv[1])
    letters = ranges(c for c, k in cats.items() if k[0] == "L")
    numbers = ranges(c for c, k in cats.items() if k[0] == "N")
    print(f"""/*
 * unicode_tables.h — GENERATED by tools/gen_unicode_tables.py from Unicode 16.0
 * UnicodeData.txt. Do not edit by hand.
 *
 * k_unicode_letter:  General_Category L* (Lu, Ll, Lt, Lm, Lo)  = \\p{{L}}
 * k_unicode_number:  General_Category N* (Nd, Nl, No)          = \\p{{N}}
 * Sorted, non-overlapping, inclusive ranges for binary search.
 */
#ifndef BITNET_UNICODE_TABLES_H
#define BITNET_UNICODE_TABLES_H

#include <stdint.h>

#define UNICODE_TABLES_VERSION "16.0.0"

{emit("k_unicode_letter", letters)}
#define UNICODE_LETTER_RANGES {len(letters)}

{emit("k_unicode_number", numbers)}
#define UNICODE_NUMBER_RANGES {len(numbers)}

#endif /* BITNET_UNICODE_TABLES_H */""")


if __name__ == "__main__":
    main()
